# This workflow will install Python dependencies, run tests and lint with a single version of Python
# 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: readme.md

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure || true}}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false    
    steps:
    - uses: actions/checkout@v2
    - name: Set up 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install requests 
    - name: Clean Readme
      run: |
        rm README.md
        date >> README.md 
        echo "strDate=$(TZ=UTC date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
    - name: Generate README
      run: python generate.py
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*
        tag: ${{env.strDate}}
        file_glob: true
        overwrite: true
        release_name: ${{env.strDate}}
    
    - name: Commit README
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update README"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
